version: '3.8'

services:
  # Servicio Brain - Motor de Decisiones
  brain:
    build:
      context: .
      dockerfile: services/brain/Dockerfile
    container_name: oraculo-brain
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_API_SECRET=${BINANCE_API_SECRET}
      - BRAIN_ANALYSIS_INTERVAL=${BRAIN_ANALYSIS_INTERVAL:-3600}
      - BRAIN_LOG_LEVEL=${BRAIN_LOG_LEVEL:-INFO}
      - BRAIN_DEBUG=${BRAIN_DEBUG:-false}
      - BRAIN_DEV_MODE=${BRAIN_DEV_MODE:-false}
    volumes:
      - ./logs:/app/logs
      - ./shared:/app/shared
    restart: unless-stopped
    networks:
      - oraculo-network

  # Servicio Grid - Trading Automático
  grid:
    build:
      context: .
      dockerfile: services/grid/Dockerfile
    container_name: oraculo-grid
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_API_SECRET=${BINANCE_API_SECRET}
      - PAPER_TRADING_API_KEY=${PAPER_TRADING_API_KEY}
      - PAPER_TRADING_SECRET_KEY=${PAPER_TRADING_SECRET_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - TRADING_MODE=${TRADING_MODE:-sandbox}
      - MONITORING_INTERVAL_HOURS=${MONITORING_INTERVAL_HOURS:-1}
    volumes:
      - ./logs:/app/logs
      - ./shared:/app/shared
    depends_on:
      - brain
    restart: unless-stopped
    networks:
      - oraculo-network

  # Servicio News - Análisis de Noticias
  news:
    build:
      context: .
      dockerfile: services/news/Dockerfile
    container_name: oraculo-news
    ports:
      - "8003:8003"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
      - REDDIT_USER_AGENT=${REDDIT_USER_AGENT}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - NEWS_COLLECTION_INTERVAL=${NEWS_COLLECTION_INTERVAL:-3600}
      - SENTIMENT_ANALYSIS_INTERVAL=${SENTIMENT_ANALYSIS_INTERVAL:-1800}
    volumes:
      - ./logs:/app/logs
      - ./shared:/app/shared
    restart: unless-stopped
    networks:
      - oraculo-network

  # Servicio Hype - Detección de Hype
  hype:
    build:
      context: .
      dockerfile: services/hype/Dockerfile
    container_name: oraculo-hype
    ports:
      - "8004:8004"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
      - REDDIT_USER_AGENT=${REDDIT_USER_AGENT}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - HYPE_SCAN_INTERVAL=${HYPE_SCAN_INTERVAL:-300}
      - HYPE_ALERT_THRESHOLD=${HYPE_ALERT_THRESHOLD:-10}
    volumes:
      - ./logs:/app/logs
      - ./shared:/app/shared
    restart: unless-stopped
    networks:
      - oraculo-network

  # Servicio Trend - Trend Following Bot
  trend:
    build:
      context: .
      dockerfile: services/trend/Dockerfile
    container_name: oraculo-trend
    ports:
      - "8005:8005"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_API_SECRET=${BINANCE_API_SECRET}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - TREND_ANALYSIS_TIMEFRAME=${TREND_ANALYSIS_TIMEFRAME:-4h}
      - TREND_CONFIRMATION_TIMEFRAME=${TREND_CONFIRMATION_TIMEFRAME:-1h}
      - TREND_MIN_SIGNAL_CONFIDENCE=${TREND_MIN_SIGNAL_CONFIDENCE:-0.7}
      - TREND_MAX_POSITIONS_PER_SYMBOL=${TREND_MAX_POSITIONS_PER_SYMBOL:-1}
      - TREND_DEFAULT_STOP_LOSS_PERCENT=${TREND_DEFAULT_STOP_LOSS_PERCENT:-3.0}
      - TREND_DEFAULT_TAKE_PROFIT_PERCENT=${TREND_DEFAULT_TAKE_PROFIT_PERCENT:-9.0}
      - TREND_DEFAULT_TRAILING_STOP_PERCENT=${TREND_DEFAULT_TRAILING_STOP_PERCENT:-2.0}
      - TREND_MAX_POSITION_SIZE_PERCENT=${TREND_MAX_POSITION_SIZE_PERCENT:-10.0}
      - TREND_MARKET_ANALYSIS_INTERVAL=${TREND_MARKET_ANALYSIS_INTERVAL:-15}
      - TREND_TRADE_EXECUTION_INTERVAL=${TREND_TRADE_EXECUTION_INTERVAL:-5}
      - TREND_POSITION_MANAGEMENT_INTERVAL=${TREND_POSITION_MANAGEMENT_INTERVAL:-2}
      - TREND_LOG_LEVEL=${TREND_LOG_LEVEL:-INFO}
    volumes:
      - ./logs:/app/logs
      - ./shared:/app/shared
    depends_on:
      - brain
    restart: unless-stopped
    networks:
      - oraculo-network

networks:
  oraculo-network:
    driver: bridge 